executable = conda_wrapper_fine.sh

LOGFILE = $(LOGFILE:finetuning)

EXTRA_ARGS   = $(EXTRA_ARGS:)
arguments    = python finetuning_skip.py $(EXTRA_ARGS)
# arguments  = python finetuning_skip.py

output     = logs_finetuning/$(LOGFILE).out
error      = logs_finetuning/$(LOGFILE).err
log        = logs_finetuning/$(LOGFILE).log
getenv     = True


#Requirements = CUDADriverVersion >= 12.0
#Requirements = CUDADriverVersion >= 12.0 && (regexp("A100", TARGET.CUDADeviceName) || regexp("A40", TARGET.CUDADeviceName))
Requirements = CUDADriverVersion >= 12.0 && regexp("A100", TARGET.CUDADeviceName) 

+request_gpus = 1
#request_cpus   = 1
request_memory = 64 GB



#queue 31
#Requirements = TARGET.vm_name == "its-u20-nfs-20210413" && regexp("CRUSH", TARGET.name) 
queue 
